* Dump 0x20 bytes of stack memory when dumping the register content.
PSPReverse/PSPEmu pull request #1
Opened 2020-02-17 10:49 UTC by RobertBuhren

2020-02-18 08:57 UTC, AlexanderEichner requested changes

2020-02-18 08:57 UTC, AlexanderEichner commented on psp-core.c
> +    rc = PSPEmuCoreMemRead(hCore, au32Reg[PSPCOREREG_SP] - cwLen, awStack, sizeof(awStack));
The address calculation "au32Reg[PSPCOREREG_SP] - cwLen" looks wrong, it should be "au32Reg[PSPCOREREG_SP] - cwLen * sizeof(uint32_t)" most likely. I'd prefer the following for reading the stack:

uint32_t au32Stack[8];
rc = PSPEmuCoreMemRead(hCore, au32Reg[PSPCOREREG_SP] - sizeof(au32Stack), &au32Stack[0], sizeof(au32Stack));
if (!rc)
...

2020-02-18 08:57 UTC, AlexanderEichner commented on psp-core.c
> +
Blank line can be deleted

2020-02-18 08:57 UTC, AlexanderEichner commented on psp-core.c
> +              au32Reg[PSPCOREREG_SP] -0x1c, awStack[0], au32Reg[PSPCOREREG_SP] -0x18, awStack[1],
Space between - and 0x1c etc., renaming to au32Stack

2020-02-18 08:57 UTC, AlexanderEichner commented on psp-core.c
> +      printf( "Stack:\n"
Proper 4 spaces indentation please :P

2020-02-18 19:08 UTC, RobertBuhren reviewed
:+1:

2020-02-22 14:23 UTC, merged

2020-02-22 14:23 UTC, AlexanderEichner commented
Merged, thanks!